project: AgentScope-ReAct
name: GSM8K-Qwen3-1.7B
# directory to save checkpoints, default to ./checkpoints if TRINITY_CHECKPOINT_ROOT_DIR not set
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: multi_step_grpo  # a GRPO-based algorithm for multi-step reasoning
  repeat_times: 8  # repeat each training sample 8 times
cluster:
  node_num: 1  # cluster with 1 node
  gpu_per_node: 2  # each node has 2 GPUs
buffer:
  total_epochs: 1  # run taskset for 1 epoch
  batch_size: 32  # each step contains 32 samples from taskset
  train_batch_size: 256  # trainer batch size is 256 (multi-step reasoning generate more training samples)
explorer:
  runner_per_model: 16  # each model has 16 runners for parallel rollout
  max_timeout: 600  # max timeout for each rollout is 600 seconds
synchronizer:
  sync_style: dynamic_by_explorer
  sync_method: 'nccl'
  sync_interval: 2
  sync_timeout: 1800  # wait for 30 minutes
trainer:
  save_interval: 100  # save checkpoint every 100 steps
  use_dynamic_bsz: true
  ulysses_sequence_parallel_size: 1  # use sequence parallelism to reduce memory usage
monitor:
  monitor_type: tensorboard  # here we use tensorboard, you can also use wandb, mlflow or swanlab
